### ISSUE TITLE
Dead link to tutorial info page

### ISSUE THREAD

**Issue by nmingotti** [pbella/OMeta-Cuis#1]
This link is gone: 
http://randomsamples.info/project/OMetaCuis

**Comment by pbella** [comment]
Nicola,

Thanks for reporting this.  I think I used to have some notes there that I
rolled into the github package/examples a while ago.  The link will be
removed with the next commit.

Thanks,
Phil

**Comment by nmingotti** [comment]
Hi Phil,

ok, I will look into the package examples then !

please close the issue when you remove the link. I keep it here only for you as a reminder, for me it is closed.

bye
Nicola

**Comment by pbella** [comment]
Finally got the fix committed... apologies for the delay
